name: Download

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
         wget https://archive.org/download/tiny-10-NTDEV/tiny10%2023h1%20x64.iso
         mv "tiny10 23h1 x64.iso" tiny10.iso
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          tiny10.iso
        tag_name: latest
